language: c

sudo: false

matrix:
  include:
  - env:
    addons: {apt: {packages: [libgmp-dev]}}

cache:
  directories:
  - $HOME/.stack
  - $HOME/.local

before_install:
- export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
- mkdir -p ~/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --version

install:
- stack setup --no-terminal

script:
- stack build
- stack test --test-arguments='--plain'


notifications:
  slack:
    secure: g0NP1tkOe3+kI6O0Q1mgT/jPaLjxQ31J26MWouicu2F1Y3p73qTvv/QsOkafRMZDn07HlzgviCP25r7Ytg32pUAFvOh4U4MT2MpO0jUVVGPi4ZiwB+W5AH+HlDtJSickeSZ0AjXZSaGv8nQNegWkeaLQgLBIzrTHU8s0Y9K+whQ=
