language: haskell

ghc:
 - 7.10
 - 7.8
 - 7.6
 - 7.4

before_install:
  - cabal update
  - cabal install Cabal
  - cabal install cabal-install
  - export PATH=~/.cabal/bin:$PATH
  - cabal --version
  - cabal sandbox init
  - for i in `cat REPOS`; do git clone http://github.com/haskell-distributed/$i; done
  - for i in `cat REPOS`; do cabal sandbox add-source $i; done
  - sudo apt-get update -qq
  - sudo apt-get install -qq binutils-dev

install:
  # Don't run tests for dependencies.
  - cabal install --only-dependencies

script:
  - cabal install
  - cabal install --enable-tests -j1 distributed-process-tests --run-tests
