exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
lsi: false
auto: true
pygments: true
safe: true

title: Cloud Haskell
tagline: Erlang-style concurrency for Haskell

author:
  name: Tim Watson
  email: watson.timothy@gmail.com
  github: hyperthunk
  twitter: hyperthunk

production_url: http://hyperthunk.github.com/website-next-preview
